CREATE TABLE Flight (FLIGHT_ID INT PRIMARY KEY, DEPARTURES_SCHEDULED INT,DEPARTURES_PERFORMED INT,
                     PAYLOAD INT, SEATS INT, PASSENGERS INT, FREIGHT INT, MAIL INT, DISTANCE INT,
                     DISTANCE_GROUP INT, RAMP_TO_RAMP INT, AIR_TIME INT);
                    
CREATE TABLE Timeframe (YEAR INT,QUARTER INT, MONTH INT);
CREATE TABLE Aircraft (AIRCRAFT_TYPE INT,CLASS VARCHAR(2),AIRCRAFT_GROUP INT,AIRCRAFT_CONFIG INT, PRIMARY KEY (AIRCRAFT_TYPE, CLASS));

CREATE TABLE Airport (AIRPORT_ID INT PRIMARY KEY,AIRPORT_SEQ_ID INT,CITY_MARKET_ID INT,ORIGIN_DESTINATION VARCHAR(5),
                      CITY_NAME VARCHAR(40),STATE_ABR VARCHAR(3),STATE_FIPS INT,STATE_NM VARCHAR(30),WAC INT);

/*CREATE TABLE Carrier (UNIQUE_CARRIER_ENTITY VARCHAR(15),AIRLINE_ID INT,
                      CARRIER VARCHAR (10),CARRIER_ENTITY  VARCHAR(7),
                      CARRIER_NAME  VARCHAR(80),UNIQUE_CARRIER  VARCHAR(15),
                      UNIQUE_CARRIER_NAME  VARCHAR(80),WAC INT,CARRIER_GROUP INT,
                      CARRIER_GROUP_NEW INT,REGION  VARCHAR(20),
                      START_DATE_SOURCE  VARCHAR(15),THRU_DATE_SOURCE VARCHAR(15),PRIMARY KEY (UNIQUE_CARRIER_ENTITY,START_DATE_SOURCE));
  */
CREATE TABLE Carrier ( UNIQUE_CARRIER_ENTITY VARCHAR(15) PRIMARY KEY,UNIQUE_CARRIER VARCHAR(15),
                      AIRLINE_ID INT,UNIQUE_CARRIER_NAME VARCHAR(80),REGION VARCHAR(20),CARRIER_GROUP INT ); 

CREATE TABLE Maintable(FLIGHT_ID INT REFERENCES Flight,UNIQUE_CARRIER_ENTITY VARCHAR(15) REFERENCES Carrier,
                       ORIGIN_AIRPORT_ID INT REFERENCES Airport,DEST_AIRPORT_ID INT REFERENCES Airport,YEAR INT REFERENCES Timeframe,
                       AIRCRAFT_TYPE INT, CLASS VARCHAR(2), FOREIGN KEY (AIRCRAFT_TYPE, CLASS) REFERENCES Aircraft(AIRCRAFT_TYPE, CLASS));



COPY flight(FLIGHT_ID,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,
            PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,
            DISTANCE_GROUP,RAMP_TO_RAMP,AIR_TIME)
FROM 'H:\databases files\after\databases 1 - Flight.csv' DELIMITER ',' CSV HEADER;

COPY Timeframe(YEAR,QUARTER,MONTH)
FROM 'H:\databases files\after\databases 1 - Timeframe.csv' DELIMITER ',' CSV HEADER;


COPY Aircraft (AIRCRAFT_TYPE,CLASS,AIRCRAFT_GROUP,AIRCRAFT_CONFIG)
FROM 'H:\databases files\after\databases 1 - Aircraft.csv' DELIMITER ',' CSV HEADER;

COPY Airport(AIRPORT_ID,AIRPORT_SEQ_ID,CITY_MARKET_ID,ORIGIN_DESTINATION,CITY_NAME,STATE_ABR,STATE_FIPS,STATE_NM,WAC)
FROM 'H:\databases files\after\databases 1 - Airport.csv' DELIMITER ',' CSV HEADER;

/*COPY Carrier(UNIQUE_CARRIER_ENTITY,AIRLINE_ID,CARRIER,CARRIER_ENTITY,
             CARRIER_NAME,UNIQUE_CARRIER,UNIQUE_CARRIER_NAME,WAC,
             CARRIER_GROUP,CARRIER_GROUP_NEW,REGION,START_DATE_SOURCE,THRU_DATE_SOURCE)
FROM 'H:\databases files\after\databases 1 - Carrier.csv' DELIMITER ',' CSV HEADER;
*/

COPY Carrier(UNIQUE_CARRIER_ENTITY,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,REGION,CARRIER_GROUP)
FROM 'H:\databases files\after\databases 1 - Carrier.csv' DELIMITER ',' CSV HEADER;

COPY Maintable (FLIGHT_ID,UNIQUE_CARRIER_ENTITY,ORIGIN_AIRPORT_ID,DEST_AIRPORT_ID,YEAR,AIRCRAFT_TYPE,CLASS)
FROM 'H:\databases files\after\databases 1 - Main Table.csv' DELIMITER ',' CSV HEADER;
