CREATE TABLE Flight (FLIGHT_ID INT PRIMARY KEY, DEPARTURES_SCHEDULED INT,DEPARTURES_PERFORMED INT,
                     PAYLOAD INT, SEATS INT, PASSENGERS INT, FREIGHT INT, MAIL INT, DISTANCE INT,
                     DISTANCE_GROUP INT, RAMP_TO_RAMP INT, AIR_TIME INT);
                    
CREATE TABLE Timeframe (YEAR INT,QUARTER INT, MONTH INT);

CREATE TABLE Aircraft (AIRCRAFT_TYPE INT,CLASS VARCHAR(2),AIRCRAFT_GROUP INT,AIRCRAFT_CONFIG INT, PRIMARY KEY (AIRCRAFT_TYPE, CLASS));

CREATE TABLE Airport (AIRPORT_ID INT PRIMARY KEY,AIRPORT_SEQ_ID INT,CITY_MARKET_ID INT,ORIGIN_DESTINATION VARCHAR(5),
                      CITY_NAME VARCHAR(40),STATE_ABR VARCHAR(3),STATE_FIPS INT,STATE_NM VARCHAR(30),WAC INT);

CREATE TABLE Carrier ( UNIQUE_CARRIER_ENTITY VARCHAR(15) PRIMARY KEY,UNIQUE_CARRIER VARCHAR(15),
                      AIRLINE_ID INT,UNIQUE_CARRIER_NAME VARCHAR(80),REGION VARCHAR(20),CARRIER_GROUP INT ); 

CREATE TABLE Maintable(FLIGHT_ID INT REFERENCES Flight,UNIQUE_CARRIER_ENTITY VARCHAR(15) REFERENCES Carrier,
                       ORIGIN_AIRPORT_ID INT REFERENCES Airport,DEST_AIRPORT_ID INT REFERENCES Airport,YEAR INT REFERENCES Timeframe,
                       AIRCRAFT_TYPE INT, CLASS VARCHAR(2), FOREIGN KEY (AIRCRAFT_TYPE, CLASS) REFERENCES Aircraft(AIRCRAFT_TYPE, CLASS));
