COPY flight(FLIGHT_ID,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,
            PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,
            DISTANCE_GROUP,RAMP_TO_RAMP,AIR_TIME)
FROM 'H:\databases files\after\databases 1 - Flight.csv' DELIMITER ',' CSV HEADER;

COPY Timeframe(YEAR,QUARTER,MONTH)
FROM 'H:\databases files\after\databases 1 - Timeframe.csv' DELIMITER ',' CSV HEADER;

COPY Aircraft (AIRCRAFT_TYPE,CLASS,AIRCRAFT_GROUP,AIRCRAFT_CONFIG)
FROM 'H:\databases files\after\databases 1 - Aircraft.csv' DELIMITER ',' CSV HEADER;

COPY Airport(AIRPORT_ID,AIRPORT_SEQ_ID,CITY_MARKET_ID,ORIGIN_DESTINATION,CITY_NAME,STATE_ABR,STATE_FIPS,STATE_NM,WAC)
FROM 'H:\databases files\after\databases 1 - Airport.csv' DELIMITER ',' CSV HEADER;

COPY Carrier(UNIQUE_CARRIER_ENTITY,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,REGION,CARRIER_GROUP)
FROM 'H:\databases files\after\databases 1 - Carrier.csv' DELIMITER ',' CSV HEADER;

COPY Maintable (FLIGHT_ID,UNIQUE_CARRIER_ENTITY,ORIGIN_AIRPORT_ID,DEST_AIRPORT_ID,YEAR,AIRCRAFT_TYPE,CLASS)
FROM 'H:\databases files\after\databases 1 - Main Table.csv' DELIMITER ',' CSV HEADER;
